== Connect Jersey Spring

There are a few things about this artifact that make it particular to the *connect.cd* platform.
 
* It is using delayed configuration to expose the Jersey servlets, surfaced by the ServletModule capability.
* It is using StickyCode configuration injection to expose configuration as to how the filtering system works. See
 `JerseyFilteringConfiguration`. This allows overriding logging of:

- full log excludes (e.g. excluding references to metric, liveness and readyness polling) from REST logs
- content logging (excluding content from sensitive methods, such as passwords) from the logs.
- sizing the content of the logs

* It re-writes the logs that come from the Jersey logs so  they have a different priority and write out extra
meta-data (such as return values, swap their content into the `payload` field, etc).

* Exposes a `JerseyModule` that can be overridden to register multiple Jersey endpoints
* Comes fully configured for generaly use cases, but can be overridden - see `JerseyApplicationBase` for the default
and `JerseyModule` for how to override.

=== Use

* Include this module
* Derive from JerseyModule and pass in your classes to be registered, they do not need to be registered with Spring here.
* Use @Import or similar to include your JerseyModules.

==== Notes/ToDo

- ideally urls such as metrics, etc should be discoverable from the platform so they are automatically configured
